backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)
  media_folder: "public/images"
  public_folder: "/images"
  collections:
  - name: "opera" # Used in routes, e.g., /admin/collections/blog
    label: "Opera" # Used in the UI
    folder: "opere" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
